#!/bin/bash

export PYTHONPATH=$EIGER_DETECTOR/data/tools/python/
${NUMA}${ODIN_DATA}/prefix/bin/meta_writer -w metalistener.eiger_meta_writer.EigerMetaWriter -i ${IP_LIST} --staticlogfields beamline=$${BEAMLINE},detector="Eiger${SENSOR}" --logserver "graylog2.diamond.ac.uk:12210"
