#!/bin/bash

SCRIPT_DIR="$$( cd "$$( dirname "$$0" )" && pwd )"

$NUMA$ODIN_DATA/bin/frameReceiver --iothreads $IO_THREADS --ctrl=tcp://0.0.0.0:$CTRL_PORT --config=$$SCRIPT_DIR/fr$NUMBER.json --log-config $$SCRIPT_DIR/log4cxx.xml
