#!/bin/bash

SCRIPT_DIR="$$( cd "$$( dirname "$$0" )" && pwd )"

cd $OD_ROOT
${NUMA}prefix/bin/frameReceiver --sharedbuf=exc_buf_$BUFFER_IDX -m $SHARED_MEMORY --iothreads $IO_THREADS --ctrl=tcp://0.0.0.0:$CTRL_PORT --ready=tcp://127.0.0.1:$READY_PORT --release=tcp://127.0.0.1:$RELEASE_PORT --logconfig $$SCRIPT_DIR/log4cxx.xml
