#!/bin/bash

cd $OD_ROOT
prefix/bin/frameReceiver --sharedbuf=exc_buf_$BUFFER_IDX -m $SHARED_MEMORY --ctrl=tcp://0.0.0.0:$CTRL_PORT --ready=tcp://127.0.0.1:$READY_PORT --release=tcp://127.0.0.1:$RELEASE_PORT --logconfig $LOG_CONFIG
