#!/bin/bash

numactl --membind=0 --cpunodebind=0 ${APP_PATH}/bin/${APP_NAME} ${WRITER} ${SENSOR_SHAPE} --data-endpoints ${DATA_ENDPOINTS} --static-log-fields beamline=$${BEAMLINE},detector="${DETECTOR_MODEL}" --log-server "graylog-log-target.diamond.ac.uk:12210"
