#!/bin/bash

SCRIPT_DIR="$$( cd "$$( dirname "$$0" )" && pwd )"

$ODIN_SERVER --config=$$SCRIPT_DIR/$CONFIG --logging=info --access_logging=ERROR --graylog_server graylog-log-target.diamond.ac.uk:12210 $EXTRA_PARAMS
