#!/bin/sh
# This file was automatically generated on Mon 22 Apr 2024 10:15:48 BST from
# source: /scratch/development/odin/ADOdin/etc/makeIocs/eiger.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi


exec ./eiger steiger.boot
