TOP = ../..
include $(TOP)/configure/CONFIG

DIRS := $(DIRS) odin
DIRS := $(DIRS) eiger
DIRS := $(DIRS) excalibur
DIRS := $(DIRS) tristan
DIRS := $(DIRS) arc
DIRS := $(DIRS) xspress

include $(TOP)/configure/RULES_DIRS
