# This file was automatically generated on Wed 10 Apr 2024 09:51:49 BST from
# source: /dls/science/users/hvc52853/OdinDEV/ADOdin/etc/makeIocs/xspress.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(INSTALL)"

epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES", '7000000'
epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(INSTALL)"

dbLoadDatabase "dbd/xspress.dbd"
xspress_registerRecordDeviceDriver(pdbbase)

callbackSetQueueSize(400000)

# odinDataDriverConfig(const char * portName, const char * serverPort, int odinServerPort, int odinDataCount, const char * datasetName, const char * detectorName, int maxBuffers, size_t maxMemory)
odinDataDriverConfig("ODN.OD", "127.0.0.1", 8888, 2, "data", "xspress", 0, 0)

# odinDetectorConfig(const char * portName, const char * serverPort, int odinServerPort, const char * detectorName, int maxBuffers, size_t maxMemory, int priority, int stackSize)
odinDetectorConfig("ODN.CAM", "127.0.0.1", 8888, "xspress", 0, 0)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize, maxThreads)
NDStdArraysConfigure("ODN.ARR", 100, 0, "ODN.CAM", 0, 0, 0, 0, 0, 1)

# Final ioc initialisation
# ------------------------
cd "$(INSTALL)"
dbLoadRecords 'db/xspress_expanded.db'
iocInit

dbpf "XSPRESS:OD:ReadStatus.SCAN", "7"

dbpf "XSPRESS:CAM:ReadStatus.SCAN", "7"

dbpf "XSPRESS:CAM:CONFIG_PATH", "/dls_sw/i18/epics/xspress3/xspress3.cube+cube/settings"

dbpf "XSPRESS:CAM:LiveViewEndpoint", "tcp://127.0.0.1:15510"

dbpf "XSPRESS:CAM:RECONFIGURE", "1"

dbpf "XSPRESS:OD:ImageHeight", "1"

dbpf "XSPRESS:OD:ImageWidth", "4096"

dbpf "XSPRESS:OD:NumFramesChunks", "1"

dbpf "XSPRESS:OD:NumRowChunks", "1"

dbpf "XSPRESS:OD:NumColChunks", "4096"
