#!/bin/sh
# This file was automatically generated on Wed 10 Apr 2024 09:51:49 BST from
# source: /dls/science/users/hvc52853/OdinDEV/ADOdin/etc/makeIocs/xspress.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi


exec ./xspress stxspress.boot
