/* This file was automatically generated on Wed 10 Apr 2024 09:51:49 BST from
 * source: /dls/science/users/hvc52853/OdinDEV/ADOdin/etc/makeIocs/xspress.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

