# These are the IOCs we should create. The IOC should either have the same name
# as an xml or py file in etc/makeIocs, or be suffixed with _sim to create a
# simulation from that same file
CUSTOM_IOCS := excalibur eiger4M eiger9M eiger16M tristan
IOCS += $(CUSTOM_IOCS)

# These are the dirs that each IOC lives in
CUSTOM_DIRS = $(patsubst %, $(TOP)/iocs/%, $(CUSTOM_IOCS))
IOC_DIRS := $(patsubst %, $(TOP)/iocs/%, $(IOCS))
